[WIP] Feat/text by text
smartmind-team/thanosql-docs pull request #118
Opened 2022-10-07 06:32 UTC by yeemh

## Check Point

1. 참조 -> BUUILD MODEL -> 'BUILD MODEL'을 통해 사용 가능한 인공지능 모델
    * SBERT 모델
        - [ ] 순서 확인 필요
    * , 앞에 띄어쓰기 삭제
2. 참조 -> ThanoSQL Pre-built Model Statement Reference -> SBERT 추가
    - [ ] 순서 확인 필요

- 난이도 조절 (별 한 개..?)
- SIMCLR에서 아래 부분 없어도 되는지?
```
query_statement:
    query_expr
``` 
- text 모델 기준?(albert_electra VS sbert)

2022-10-11 08:19 UTC, sk37025 approved these changes

2022-10-11 08:20 UTC, sk37025 commented
한국어 확인 완료했습니다. 👍

2022-10-13 00:26 UTC, inwookie requested changes
다 확인 했습니다! 
이거만 수정하면 merge 해도 될거 같아요.

2022-10-13 00:26 UTC, inwookie commented on docs/en/tutorials/algorithm_list.md
> +                    <br>Use ThanoSQL's text-to-text search model to search for the desired document in text.</br>
```suggestion
                    <br>Use ThanoSQL's text-to-text search model to search for the desired text in the document.</br>
```

2022-10-13 00:45 UTC, yeemh commented on docs/en/tutorials/algorithm_list.md
> +                    <br>Use ThanoSQL's text-to-text search model to search for the desired document in text.</br>
@inwookie 
<br>Use ThanoSQL's text-to-text search model to search for the desired document.</br>
로 바꿨습니다.
확인해주세요

2022-10-13 00:51 UTC, inwookie approved these changes
완벽해요 👍

2022-10-19 01:24 UTC, merged