[WIP] Cu 36nhruy docs  fixed2
smartmind-team/thanosql-docs pull request #122
Opened 2022-10-28 06:59 UTC by sk37025

- COPY syntax 2차 수정

2022-10-28 06:59 UTC, lazyduo commented
Task linked: [CU-36nhruy docs 오타 및 표현 방법 수정](https://app.clickup.com/t/36nhruy)

2022-11-18 06:04 UTC, yeemh commented
@inwookie @stevensjcho review please

2022-11-21 01:06 UTC, stevensjcho commented on docs/ko/tutorials/thanosql_ml/audio_recognition/speech_recognition.md
> +본 튜토리얼을 진행하기 위해 우리는 ThanoSQL 워크스페이스 DBrkspace DB에 저장되어 있는  <mark style="background-color:#FFEC92 ">librispeech_train</mark> 테이블을 사용합니다. 아래의 쿼리문을 실행하여 테이블 내용을 확인합니다.
`DBrkspace` ??

2022-11-21 01:22 UTC, inwookie requested changes
전반적으로 `DB` 대신에 한국어는 `데이터베이스` 그리고 영어는 `database`로 통일 하면 어떨까 합니다. 이유는 통상적으로 database를 `DB`로 쓰는경우가 많지 않은거 같아서 입니다.

2022-11-21 01:22 UTC, inwookie commented on docs/en/tutorials/thanosql_ml/audio_recognition/speech_recognition.md
> +- [How to Upload to ThanoSQL workspace DB](https://docs.thanosql.ai/en/getting_started/data_upload/)
```suggestion
- [How to upload to the ThanoSQL workspace database](https://docs.thanosql.ai/en/getting_started/data_upload/)
```

이거 관련해서 thanosql-tutorial repo의 [PR](https://github.com/smartmind-team/thanosql-tutorial/pull/41)에서도 이슈 나왔었는데, 위처럼 하는게 더 좋다고 생각합니다!

2022-11-21 01:22 UTC, inwookie commented on docs/en/tutorials/thanosql_ml/classification/automl_classification.md
> +- [How to Upload to ThanoSQL workspace DB](https://docs.thanosql.ai/en/getting_started/data_upload/)
```suggestion
- [How to upload to the ThanoSQL workspace database](https://docs.thanosql.ai/en/getting_started/data_upload/)
```

2022-11-21 01:22 UTC, inwookie commented on docs/en/tutorials/thanosql_ml/classification/image_classification.md
> +- [How to Upload to ThanoSQL workspace DB](https://docs.thanosql.ai/en/getting_started/data_upload/)
```suggestion
- [How to upload to the ThanoSQL workspace database](https://docs.thanosql.ai/en/getting_started/data_upload/)
```

2022-11-21 01:22 UTC, inwookie commented on docs/en/tutorials/thanosql_ml/classification/text_classification.md
> +- [How to Upload to ThanoSQL workspace DB](https://docs.thanosql.ai/en/getting_started/data_upload/)
```suggestion
- [How to upload to the ThanoSQL workspace database](https://docs.thanosql.ai/en/getting_started/data_upload/)
```

2022-11-21 01:22 UTC, inwookie commented on docs/en/tutorials/thanosql_ml/regression/automl_regression.md
> +- [How to Upload to ThanoSQL workspace DB](https://docs.thanosql.ai/en/getting_started/data_upload/)
```suggestion
- [How to upload to the ThanoSQL workspace database](https://docs.thanosql.ai/en/getting_started/data_upload/)
```

2022-11-21 01:22 UTC, inwookie commented on docs/en/tutorials/thanosql_search/search_image_by_image.md
> +- [How to Upload to ThanoSQL workspace DB](https://docs.thanosql.ai/en/getting_started/data_upload/)
```suggestion
- [How to upload to the ThanoSQL workspace database](https://docs.thanosql.ai/en/getting_started/data_upload/)
```

2022-11-21 01:22 UTC, inwookie commented on docs/en/tutorials/thanosql_search/search_text_by_text.md
> +* [How to Upload to ThanoSQL workspace DB](https://docs.thanosql.ai/en/getting_started/data_upload/)
```suggestion
* [How to upload to the ThanoSQL workspace database](https://docs.thanosql.ai/en/getting_started/data_upload/)
```

2022-11-21 01:22 UTC, inwookie commented on docs/en/how-to_guides/ThanoSQL_connecting/rest_api_thanosql_insert.md
> +# **How to Upload to ThanoSQL workspace DB**
```suggestion
# **How to Upload to ThanoSQL Workspace Database**
```
이거는 title이니깐 다 uppercase 하던지 lowercase로 하던지 하는게 좋을거 같아요.

2022-11-23 09:46 UTC, yeemh commented on docs/en/tutorials/thanosql_ml/audio_recognition/speech_recognition.md
> +- [How to Upload to ThanoSQL workspace DB](https://docs.thanosql.ai/en/getting_started/data_upload/)
해당 내용 확정되면 튜토리얼도 맞춰야합니다.

2022-11-23 10:13 UTC, yeemh commented on docs/ko/tutorials/thanosql_ml/audio_recognition/speech_recognition.md
> +본 튜토리얼을 진행하기 위해 우리는 ThanoSQL 워크스페이스 DBrkspace DB에 저장되어 있는  <mark style="background-color:#FFEC92 ">librispeech_train</mark> 테이블을 사용합니다. 아래의 쿼리문을 실행하여 테이블 내용을 확인합니다.
튜토리얼 내용은 #137 에서 변경되어서 resolve 해두겠습니다.

2022-11-23 10:15 UTC, yeemh commented
> 전반적으로 `DB` 대신에 한국어는 `데이터베이스` 그리고 영어는 `database`로 통일 하면 어떨까 합니다. 이유는 통상적으로 database를 `DB`로 쓰는경우가 많지 않은거 같아서 입니다.

해당 내용 관련해서도 정하도록 하죠

2022-11-23 10:23 UTC, yeemh commented on docs/en/how-to_guides/ThanoSQL_connecting/rest_api_thanosql_insert.md
> +# **How to Upload to ThanoSQL workspace DB**
> 이거는 title이니깐 다 uppercase 하던지 lowercase로 하던지 하는게 좋을거 같아요.

해당 내용은 #134 로 옮겨두겠습니다.

2022-11-24 00:48 UTC, inwookie commented
@yeemh

1. DB -> database 
2. title ->  대문자 or 소문자 통일
3. grammar -> the 붙이는거 

이번 PR과는 별개로 따로 관리 하겠다는 건가요?

2022-11-24 01:27 UTC, yeemh commented
> @yeemh
> 
> 1. DB -> database
> 2. title ->  대문자 or 소문자 통일
> 3. grammar -> the 붙이는거
> 
> 이번 PR과는 별개로 따로 관리 하겠다는 건가요?

1. -> https://github.com/smartmind-team/thanosql-docs/pull/122#issuecomment-1324824507
2. -> https://github.com/smartmind-team/thanosql-docs/pull/122#discussion_r1030262138
3.-> #134 에서 수정

2022-11-24 01:28 UTC, yeemh approved these changes

2022-11-24 01:58 UTC, inwookie approved these changes
🔥

2022-11-24 01:58 UTC, stevensjcho approved these changes
👍

2022-11-24 02:00 UTC, merged