Syntax/preprocess
smartmind-team/thanosql-docs pull request #125
Opened 2022-11-01 08:51 UTC by jyoon0808

preprocess 구문 추가

2022-11-04 07:12 UTC, sk37025 commented on docs/ko/how-to_guides/ThanoSQL_query/PREPROCESS_SYNTAX.md
> +사용자는 "__PREPROCESS__" 문을 사용하여 본인의 데이터(텍스트, 이미지, 오디오, 비디오)를 제공되는 전처리 방법으로 가공하고 ThanoSQL DB 안의 데이터 테이블로 생성합니다.
사용자가 본인의 데이터를 ThanoSQL이 제공하는 전처리 방법으로 가공하는 문법인거죠? 
그러면 멘트를 본인의 데이터를 ThanoSQL이 제공하는 전처리 방법으로 가공하고로 바꾸는게 좋을 것 같아요

2022-11-04 07:14 UTC, sk37025 commented on docs/ko/how-to_guides/ThanoSQL_query/PREPROCESS_SYNTAX.md
> +
제가 PREPROCESS가 무슨 역할을 하는지 정확히 이 옵션 설명만 가지고는 모르겠어요 ㅜㅜ 추후 사용법에 대한 얘기를 나눠봐야할 것 같습니다. 
그리고 테이터..! ㅎㅎ

2022-11-04 07:15 UTC, sk37025 requested changes
docs 작성 끝난 이후에 다시 논의해봐야할 것  같습니다!

2022-11-04 07:16 UTC, sk37025 commented on docs/ko/how-to_guides/ThanoSQL_query/PREPROCESS_SYNTAX.md
> +사용자는 "__PREPROCESS__" 문을 사용하여 본인의 데이터(텍스트, 이미지, 오디오, 비디오)를 제공되는 전처리 방법으로 가공하고 ThanoSQL DB 안의 데이터 테이블로 생성합니다.
사용자가 본인의 데이터를 ThanoSQL이 제공하는 전처리 방법으로 가공하는 문법인거죠? 
그러면 멘트를 본인의 데이터를 ThanoSQL이 제공하는 전처리 방법으로 가공하고로 바꾸는게 좋을 것 같아요

2022-11-25 02:27 UTC, yeemh commented
@jyoon0808 FUNCTION으로 대체됨으로 닫겠습니다. 패기있게 폐기

2022-11-25 02:27 UTC, closed without merging