update: copy clause
smartmind-team/thanosql-docs pull request #131
Opened 2022-11-09 05:00 UTC by inwookie

1. `CREATE_TABLE` has been deprecated. 
2. `COPY` clause has been updated to replace `CREATE_TABLE` and also now includes copying dataframe into a DB.
3. Update in the docs has been made for both Ko and En.

2022-11-10 00:28 UTC, yeemh approved these changes
great! 👍

2022-11-10 00:58 UTC, lazyduo commented on docs/en/how-to_guides/ThanoSQL_query/COPY_SYNTAX.md
> +!!! note "__데이터 폴더 COPY 사용법__"
한글.

2022-11-10 01:04 UTC, inwookie commented on docs/en/how-to_guides/ThanoSQL_query/COPY_SYNTAX.md
> +!!! note "__데이터 폴더 COPY 사용법__"
수정 했습니다!

2022-11-10 01:37 UTC, lazyduo requested changes

2022-11-10 01:37 UTC, lazyduo commented on docs/ko/how-to_guides/ThanoSQL_query/COPY_SYNTAX.md
> +[워크스페이스에 있는 데이터 파일이나 폴더의 절대 경로 혹은 데이터프레임]
```suggestion
[ 데이터 파일 | 폴더의 절대 경로 | 데이터프레임]
```
데이터 프레임은.. python 변수로 넣어야 된다는걸 어떤식으로든 설명이 있어야 할 것 같긴해요..

2022-11-10 02:10 UTC, lazyduo approved these changes

2022-11-10 02:15 UTC, lazyduo commented
@sk37025 @inwookie @jyoon0808  @yeemh 
내용에 큰 문제는 없는데, jupyter notebook에서 변수로 있는 dataframe을 넣는다는것을 어떻게 잘 설명하면 좋을지 의견주세요. 그 부분에 대한 설명이 부족해보입니다.

2022-11-10 02:22 UTC, inwookie commented
[Pandas DataFrames](https://www.w3schools.com/python/pandas/pandas_dataframes.asp)
dataframe -> Pandas DataFrame 

dataframe 넣는 예시를 만들어서 보여줄것

2022-11-14 05:47 UTC, sk37025 requested changes
총 2가지 요청드립니다. 

1. 데이터프레임 -> 판다스의 데이터프레임으로의 표현 변환
2. 데이터프레임 활용 예시 -> 앞에 df 에 선언하는 파트 추가하기

2022-11-14 05:47 UTC, sk37025 commented on docs/ko/how-to_guides/ThanoSQL_query/COPY_SYNTAX.md
> +사용자는 "__COPY__" 구문을 사용하면 현재 ThanoSQL 워크스페이스에 있는 데이터 파일들, 데이터 폴더, 그리고 작업중인 데이터프레임을 ThanoSQL DB 안의 데이터 테이블로 생성할 수 있습니다.
"데이터프레임 -> pandas의 데이터 프레임" 이라고 구체화하는게 나을 것 같습니다.

2022-11-14 05:47 UTC, sk37025 commented on docs/ko/how-to_guides/ThanoSQL_query/COPY_SYNTAX.md
> +
이 구문앞에 데이터 테이블을 변수에 할당하는 예시 추가가 필요해 보입니다!

2022-11-14 05:47 UTC, sk37025 commented on docs/en/how-to_guides/ThanoSQL_query/COPY_SYNTAX.md
> +The "__COPY__" statement allows users to create data tables in the thanoSQL DB with their data files, data folders, and dataframe within their workspace.
'dataframe -> Pandas DataFrame' 
to specify the meaning of dataframe.

2022-11-14 05:47 UTC, sk37025 commented on docs/en/how-to_guides/ThanoSQL_query/COPY_SYNTAX.md
> +Using a dataframe:
```python
df = pd.read_csv("./diet_image_data/sample.csv") 
```

```sql
%%thanosql
COPY mytable
OPTIONS (
    overwrite=True
)
FROM df
```
으로 연결되면 보다 무슨 말인지 이해하기 쉬울것 같습니다.

2022-11-15 00:10 UTC, inwookie commented
데이터프레임 관련 내용 추가 및 한번더 검수 했습니다.

2022-11-15 01:52 UTC, sk37025 approved these changes
내용 확인했습니다.

2022-11-15 04:51 UTC, merged

2022-11-16 00:25 UTC, lazyduo reviewed
추가 수정 필요합니다.

2022-11-16 00:25 UTC, lazyduo commented on docs/en/how-to_guides/ThanoSQL_query/COPY_SYNTAX.md
> +[absolute_file_path | absolute_dir_path | dataframe]
dataframe 빠져야함 (한글도)

2022-11-16 00:25 UTC, lazyduo commented on docs/ko/how-to_guides/ThanoSQL_query/COPY_SYNTAX.md
> +%%thanosql $copy_pandas_df
```suggestion
%thanosql $copy_pandas_df
```