Fix/copy syntax
smartmind-team/thanosql-docs pull request #132
Opened 2022-11-16 02:14 UTC by inwookie

#131 에서 미쳐 고치지 못한 부분들이 있어서 다시한번 PR을 만들었습니다.

2022-11-16 02:24 UTC, sk37025 commented
%thanosql인 부분에 대하여 확인 완료했습니다. 

그나저나 %하나와 %%두개를 썼을 경우에 대하여 차이점을 확인할 수 있는 page가 딱히 없네요 

다음에 반영해야겠습니다

2022-11-16 02:24 UTC, sk37025 approved these changes

2022-11-16 02:31 UTC, lazyduo requested changes
'절대 경로' 언급에 대한 고민과 아래 코드에 대한 충분한 설명 추가 부탁합니다.
```
df_in_json = df.to_json(orient="records")
```

2022-11-16 02:36 UTC, lazyduo commented
> %thanosql인 부분에 대하여 확인 완료했습니다.
> 
> 그나저나 %하나와 %%두개를 썼을 경우에 대하여 차이점을 확인할 수 있는 page가 딱히 없네요
> 
> 다음에 반영해야겠습니다

@sk37025 @jyoon0808 Query Editor/Manager가 도입되면 파이썬 환경의 주피터와 Editor 가이드 카테고리가 분리되어야 할 것이고, 주피터 카테고리 안에 Magic 문서가 있어서 거기에서 위와 같은 내용들을 넣어주어야 합니다. Query Editor 개발에 따른 Docs 문서 구조도 고민하고 있어야 합니다.

2022-11-16 02:54 UTC, inwookie commented
> '절대 경로' 언급에 대한 고민과 아래 코드에 대한 충분한 설명 추가 부탁합니다.
> 
> ```
> df_in_json = df.to_json(orient="records")
> ```

![Screen Shot 2022-11-16 at 11 51 13 AM](https://user-images.githubusercontent.com/31870931/202071944-54a15c4a-1373-494b-8e42-57043fc5710c.png)
![Screen Shot 2022-11-16 at 11 51 24 AM](https://user-images.githubusercontent.com/31870931/202071957-2798b8fe-7008-430d-9ddc-8583020d90c3.png)

Jupyter workspace 상에서도 `home/jovyan`을 보여주고 있지 않고 COPY PATH를 했을때도 `home/jovyan`을 붙이지 않기 때문에 `절대 경로` 대신에  `경로`로 바꾸는걸로 하겠습니다! 

`df_in_json = df.to_json(orient="records")` 관련해서도 comment 더 작성해서 보충 설명 하겠습니다.

2022-11-16 04:57 UTC, inwookie commented
다시 수정 헀습니다. 

@sk37025 선근님도 Using dataframe 관련해서 부가 설명에서 어색한 점이나 수정할 부분 있으면 말씀해주세요.

2022-11-17 01:10 UTC, lazyduo approved these changes
추가로 남긴 코멘트 이외에 더 수정할 사항은 없어 보입니다. 👍🏻

2022-11-17 01:10 UTC, lazyduo commented on docs/en/how-to_guides/ThanoSQL_query/COPY_SYNTAX.md
> +# use a f-string to wrap dataframe's variable of 'df_in_json' within the COPY clause
```suggestion
# use a f-string to wrap 'df_in_json' within the COPY clause 
```
이렇게만 써도 되지 않을까요?
이유 - json 되어 있는 상태라서 dataframe 변수라고 하기 조금 애매함. 그렇다고 굳이 json화 된 변수라고 굳이 다시 말하기도 좀 그렇고, 이미 'df_in_json' 이라는 이름 자체가 충분히 설명하고 있는 듯하여 빼버리는게 낫겠다고 생각하였음.

(한글도 마찬가지)

2022-11-17 01:10 UTC, lazyduo commented on docs/ko/how-to_guides/ThanoSQL_query/COPY_SYNTAX.md
> +# Pandas Dataframe 만듭니다
```suggestion
# Pandas Dataframe을 만듭니다 
```

typo

2022-11-17 02:09 UTC, inwookie commented on docs/en/how-to_guides/ThanoSQL_query/COPY_SYNTAX.md
> +# use a f-string to wrap dataframe's variable of 'df_in_json' within the COPY clause
저도 작성 하면서 애매한 부분이라고 생각했는데 suggest 해주신대로 수정하겠습니다.

2022-11-17 02:15 UTC, inwookie commented
@sk37025 마지막 review후에 통과되면 merge 하겠습니다.

2022-11-17 04:17 UTC, sk37025 approved these changes
승인했습니다!

저도 추가적으로 바꿔야할 사항은 없어보입니다.

2022-11-17 04:23 UTC, merged