fix: add the to title
smartmind-team/thanosql-docs pull request #134
Opened 2022-11-21 02:37 UTC by yeemh

add the

2022-11-21 04:03 UTC, inwookie requested changes
수정 필요할거 같아요!

2022-11-21 04:03 UTC, inwookie commented on docs/en/getting_started/data_upload.md
> +# __How to upload your data to the ThanoSQL workspace__
```suggestion
# __How to Upload your Data to the ThanoSQL Workspace 
```
다른 file들 title보니깐 다 uppercase되어 있는거 같아서 통일 하면 좋을거 같아요. 

`rest_api_thanosql_insert.md`
- How to Upload to ThanoSQL DB -> How to Upload to the ThanoSQL Database

`rest_api_thanosql_query.md`
- How to Query Using ThanoSQL -> How to Query Using ThanoSQL 

다른 file들도 고쳐야 하는지 확인 필요 할거 같아요

2022-11-22 02:14 UTC, sk37025 approved these changes

2022-11-23 00:22 UTC, inwookie requested changes
🆘

2022-11-23 00:22 UTC, inwookie commented on docs/en/getting_started/data_upload.md
> +ThanoSQL Workspace's users can upload data using two ways as shown below.
```suggestion
The ThanoSQL workspace's users can upload data in two ways, as shown below.
```

2022-11-23 00:22 UTC, inwookie commented on docs/en/getting_started/data_upload.md
> +# __How to upload your data to the ThanoSQL Workspace__
```suggestion
# __How to Upload Your Data to the ThanoSQL Workspace__ 
```

2022-11-23 00:22 UTC, inwookie commented on docs/en/getting_started/data_upload.md
> +title: How to upload your data to the ThanoSQL Workspace
```suggestion
title: How to Upload Your Data to the ThanoSQL Workspace
```

2022-11-23 00:22 UTC, inwookie commented on docs/en/getting_started/data_upload.md
> +To upload local data to ThanoSQL Workspace, follow these steps:
```suggestion
Follow these steps to upload local data to the ThanoSQL workspace:
```

2022-11-23 00:22 UTC, inwookie commented on docs/en/getting_started/data_upload.md
>  ## __1. Uploading your local data in a workspace environment__
```suggestion
## __1. Uploading your local data into a workspace environment__
```

2022-11-23 00:22 UTC, inwookie commented on docs/en/getting_started/hello_ThanoSQL.md
> +!!! notice "How to create a query statement in the ThanoSQL Workspace"
```suggestion
!!! notice "How to create a query statement in the ThanoSQL workspace" 

```

2022-11-23 00:22 UTC, inwookie commented on docs/en/getting_started/hello_ThanoSQL.md
>      You can use either a one-line or multi-line format when writting ThanoSQL queries.
```suggestion
    You can use either a one-line or multi-line format when writing ThanoSQL queries.

```

2022-11-23 00:22 UTC, inwookie commented on docs/en/getting_started/hello_ThanoSQL.md
>      - One-line queries are primarily used when returning queries in table form and assigning tables to variables. It is also used to assign ThanoSQL cell magic and Token, as shown in step 1 and 2.
```suggestion
    - One-line queries are primarily used when returning queries in table form and assigning tables to variables. It is also used to assign ThanoSQL cell magic and a token, as shown in steps 1 and 2.

```

2022-11-23 00:22 UTC, inwookie commented on docs/en/index.md
> +                    Explain about the basic usage of ThanoSQL Workspace.
```suggestion
                    Explain the basic usage of the ThanoSQL workspace.

```

2022-11-23 00:22 UTC, inwookie commented on docs/en/how-to_guides/ThanoSQL_connecting/rest_api_thanosql_query.md
> +You can run the same queries using ThanoSQL's REST API as you would on the ThanoSQL Workspace.
```suggestion
You can run the same queries using ThanoSQL's REST API as you would on the ThanoSQL workspace.
```

2022-11-23 00:22 UTC, inwookie commented on docs/en/index.md
> +                    How to upload your data to ThanoSQL Workspace
```suggestion
                   How to Upload Your Data to the ThanoSQL Workspace
```

2022-11-23 00:22 UTC, inwookie commented on docs/en/index.md
> +                    Explain about the basic usage of ThanoSQL Workspace.
index 관련해서는 file 이름이나 title도 같이 바꿔야 하는건가요?

2022-11-23 01:24 UTC, lazyduo commented
기존 PR 제목이 수정 중인 내용과 맞지 않아 바꿨습니다.

2022-11-23 10:26 UTC, yeemh commented
issue #138 도 확인

2022-11-24 02:19 UTC, inwookie commented
제가 수정 해야하는 부분들 전체적으로 수정 끝냈습니다. 
그리고 en index.md에서 title부분이 전부다 uppercase 되어있어서 다 format 맞췄습니다.

2022-11-24 02:19 UTC, inwookie approved these changes
🔥 LGTM 
수정 완료

2022-11-24 02:27 UTC, merged