deprecate: LIST THANOSQL TUTORIAL deleted
smartmind-team/thanosql-docs pull request #135
Opened 2022-11-22 07:26 UTC by inwookie

LIST THANOSQL TUTORIAL이 삭제 됨에 따라 필요한 docs 수정입니다. Engine [PR](https://github.com/smartmind-team/thanosql-engine/pull/163)

2022-11-23 01:32 UTC, lazyduo requested changes
영어 복수를 한글로 옮겨 올 때 '들'을 쓸지 안 쓸지, '들'과 '리스트'를 혼용해서 쓰는 문제 등 Writing Rule 잡아주세요.

2022-11-23 01:32 UTC, lazyduo commented on docs/en/how-to_guides/ThanoSQL_query/LIST_SYNTAX.md
> +The "__LIST__" statement allows users to view the lastest pre-built models ("THANOSQL MODEL"), provided datasets ("THANOSQL DATASET), tables ("TABLE") and the models ("MODEL") created by the users.
```suggestion
The "__LIST__" statement allows users to view the lastest pre-built models ("THANOSQL MODEL"), provided datasets ("THANOSQL DATASET"), tables ("TABLE") and the models ("MODEL") created by the users.

```
typo

2022-11-23 01:32 UTC, lazyduo commented on docs/ko/how-to_guides/ThanoSQL_query/LIST_SYNTAX.md
> +사용자는 "__LIST__" 구문을 사용하여 현재 ThanoSQL의 Pre-built 모델들("THANOSQL MODEL"), ThanoSQL의 Dataset들("THANOSQL DATASET"), 사용자가 만든 테이블들("TABLE")과 모델들("MODEL")을 확인할 수 있습니다.
```suggestion
사용자는 "__LIST__" 구문을 사용하여 현재 ThanoSQL의 Pre-built 모델("THANOSQL MODEL"), ThanoSQL의 Dataset("THANOSQL DATASET"), 사용자가 만든 테이블("TABLE")과 모델("MODEL") 리스트를 확인할 수 있습니다. 
```
영어의 복수를 한글로 옮길 때 '들'과 같은 어미를 반드시 붙이지는 않음. 현재 다른 문장에서 `Dataset들의 리스트를 확인합니다.` 라고 되어 있는데 이런 것들도 다 `Dataset의 목록(or 리스트)을 확인합니다.` 이렇게 '들'을 빼는게 좋아보입니다.

Docs의 컨벤션을 잡아야 할 듯. 문서 정리 되어 있죠?

2022-11-23 02:30 UTC, yeemh commented on docs/ko/how-to_guides/ThanoSQL_query/LIST_SYNTAX.md
> +사용자는 "__LIST__" 구문을 사용하여 현재 ThanoSQL의 Pre-built 모델들("THANOSQL MODEL"), ThanoSQL의 Dataset들("THANOSQL DATASET"), 사용자가 만든 테이블들("TABLE")과 모델들("MODEL")을 확인할 수 있습니다.
예전에 만든게 어딨는지 몰라서 새로 만들어야합니다.

2022-11-23 02:36 UTC, inwookie commented on docs/ko/how-to_guides/ThanoSQL_query/LIST_SYNTAX.md
> +사용자는 "__LIST__" 구문을 사용하여 현재 ThanoSQL의 Pre-built 모델들("THANOSQL MODEL"), ThanoSQL의 Dataset들("THANOSQL DATASET"), 사용자가 만든 테이블들("TABLE")과 모델들("MODEL")을 확인할 수 있습니다.
일단은 `Dataset의 목록(or 리스트)을 확인합니다.` 형식으로 변경 완료 했습니다.

2022-11-23 02:52 UTC, lazyduo commented on docs/ko/how-to_guides/ThanoSQL_query/LIST_SYNTAX.md
> +사용자는 "__LIST__" 구문을 사용하여 현재 ThanoSQL의 Pre-built 모델들("THANOSQL MODEL"), ThanoSQL의 Dataset들("THANOSQL DATASET"), 사용자가 만든 테이블들("TABLE")과 모델들("MODEL")을 확인할 수 있습니다.
@yeemh tech-wiki에 넣으세요.

2022-11-23 06:31 UTC, yeemh commented on docs/ko/how-to_guides/ThanoSQL_query/LIST_SYNTAX.md
> +사용자는 "__LIST__" 구문을 사용하여 현재 ThanoSQL의 Pre-built 모델들("THANOSQL MODEL"), ThanoSQL의 Dataset들("THANOSQL DATASET"), 사용자가 만든 테이블들("TABLE")과 모델들("MODEL")을 확인할 수 있습니다.
넵 리스트업 해두는 중이고 문서화 해서 tech-wiki에 올려두겠습니다.

2022-11-23 09:38 UTC, yeemh commented on docs/ko/how-to_guides/reference.md
>  - [__COPY__](/ko/how-to_guides/ThanoSQL_query/COPY_SYNTAX/) - 워크스페이스에 있는 데이터 파일들로 ThanoSQL DB 안의 데이터 테이블 생성
```suggestion
- [__COPY__](/ko/how-to_guides/ThanoSQL_query/COPY_SYNTAX/) - 워크스페이스에 있는 데이터 파일들로 ThanoSQL 워크스페이스 DB 안의 데이터 테이블 생성
```

2022-11-24 00:50 UTC, lazyduo commented on docs/ko/how-to_guides/ThanoSQL_query/LIST_SYNTAX.md
>  [![IMAGE](/img/thanosql_syntax/query/LIST/img2.png)](/img/thanosql_syntax/query/LIST/img2.png)
여기서는 `LIST를 사용하면 이런식으로 출력된다.` 라는걸 보여주는게 목적이지 `ThanoSQL에서 이런 pre-built 모델이 실제 사용가능합니다.` 페이지가 아니므로 이거까지 Sync 맞추는거는 강요하지 않습니다.

 물론 맞추면 좋겠지만 나중에 Pre-built 모델 추가/변경 될때마다 매번 여기 이미지까지 찾아서 바꿔주고 그런 짓은 하기 너무 힘드니까 하는 얘기입니다.

2022-11-24 00:53 UTC, inwookie commented on docs/ko/getting_started/hello_ThanoSQL.md
> +[ThanoSQL 기술 문서에 있는 튜토리얼](/tutorials/algorithm_list/)에서 튜토리얼 목록을 확인할 수 있습니다. 아래 ThanoSQL문을 실행시키면 각 튜토리얼에서 사용된 데이터 테이블 리스트를 확인할 수 있습니다.
`/`를 사용하기 때문에 데이터 세트가 아닌 데이터세트가 더 자연스러운거 같아서 그렇게 하겠습니다

2022-11-24 00:55 UTC, inwookie commented on docs/ko/getting_started/hello_ThanoSQL.md
> +[ThanoSQL 기술 문서에 있는 튜토리얼](/tutorials/algorithm_list/)에서 튜토리얼 목록을 확인할 수 있습니다. 아래 ThanoSQL문을 실행시키면 각 튜토리얼에서 사용된 데이터 테이블 리스트를 확인할 수 있습니다.
"[ThanoSQL 기술 문서에 있는 튜토리얼](/tutorials/algorithm_list/)에서 튜토리얼 목록을 확인할 수 있습니다."  는 `4. 튜토리얼 가져오기`로 내리겠습니다. 

"아래 ThanoSQL문을 실행시키면 각 튜토리얼에서 사용된 데이터 세트 리스트를 확인할 수 있습니다."는 원래 있던곳에 두는게 나아보여서 그렇게 하겠습니다.

2022-11-24 01:11 UTC, inwookie commented on docs/en/how-to_guides/ThanoSQL_query/LIST_SYNTAX.md
>  [![IMAGE](/img/thanosql_syntax/query/LIST/img2.png)](/img/thanosql_syntax/query/LIST/img2.png)
이건 부탁 드릴게요 🔥

2022-11-24 01:13 UTC, inwookie commented on docs/ko/how-to_guides/ThanoSQL_query/LIST_SYNTAX.md
>  [![IMAGE](/img/thanosql_syntax/query/LIST/img2.png)](/img/thanosql_syntax/query/LIST/img2.png)
이것도 부탁 드릴게요 🔥

2022-11-24 02:18 UTC, yeemh commented on docs/ko/how-to_guides/ThanoSQL_query/LIST_SYNTAX.md
>  [![IMAGE](/img/thanosql_syntax/query/LIST/img2.png)](/img/thanosql_syntax/query/LIST/img2.png)
이름 자체가 tutorial_ 붙은게 빠지기도 했고 컬럼도 추가된게 있어서 반영해두겠습니다.

2022-11-24 02:36 UTC, inwookie commented
@yeemh  @lazyduo 
필요한 수정은 끝난거 같습니다 
merge 해도 괜찮을까요?

2022-11-24 02:37 UTC, yeemh approved these changes
🔥 LGTM
수정 완료 😎

2022-11-24 02:52 UTC, lazyduo approved these changes

2022-11-24 02:56 UTC, merged