added ko/TFT.md
smartmind-team/thanosql-docs pull request #164
Opened 2023-01-03 02:01 UTC by Indoo-Park

# Description (개요) 

TFT tech-doc in Korean 추가 PR 입니다.

## Keep in Mind

If you are creating a new statement, your first commit should always be a copy of the statement(model, ThanoSQL, function) template. This will allow reviewers to see what has been changed from the template, making the review process much more efficient.

## Type of change (작업사항)

Please delete options that are not relevant and check out the type of change.

- [x] Model statmenet creation 

Following templates can be found from the [Tech-wiki Docs](https://github.com/smartmind-team/tech-wiki/tree/main/project/thanosql/docs). 

## Writing Convention

Make sure to check out the [Writing Convention](https://github.com/smartmind-team/tech-wiki/blob/main/project/thanosql/docs/writing_convention.md). 

## Review Process

Review should be conducted by at least two people.

2023-01-03 02:55 UTC, Bing-su commented on docs/ko/how-to_guides/ThanoSQL_model/TFT.md
> +    max_epochs = 1
여기 `=` 좌우의 띄어쓰기와 `,` 좌우 띄어쓰기에 대해 일관성이 필요해보입니다.

2023-01-03 02:55 UTC, Bing-su approved these changes

2023-01-03 05:09 UTC, Indoo-Park commented on docs/ko/how-to_guides/ThanoSQL_model/TFT.md
> +    max_epochs = 1
수정했습니다 👍

2023-01-03 09:07 UTC, yeemh commented
@Indoo-Park 
여기서도
<img width="903" alt="image" src="https://user-images.githubusercontent.com/51910605/210327403-3d527486-a1b7-495c-af73-f7ead51a59cc.png">
[process_manual](https://github.com/smartmind-team/tech-wiki/blob/main/project/thanosql/docs/process_manual.md) 참고하여

.pages와 `시작하기 -> ThanoSQL 워크스페이스 사용법 -> 4. 튜토리얼 가져오기 리스트`에 URL 추가, reference.md에도 추가해 주세요.

2023-01-04 01:24 UTC, Indoo-Park commented
> @Indoo-Park 여기서도 <img alt="image" width="903" src="https://user-images.githubusercontent.com/51910605/210327403-3d527486-a1b7-495c-af73-f7ead51a59cc.png"> [process_manual](https://github.com/smartmind-team/tech-wiki/blob/main/project/thanosql/docs/process_manual.md) 참고하여
> 
> .pages와 `시작하기 -> ThanoSQL 워크스페이스 사용법 -> 4. 튜토리얼 가져오기 리스트`에 URL 추가, reference.md에도 추가해 주세요.

시작하기 -> ThanoSQL 워크스페이스 사용법 -> 4. 튜토리얼 가져오기 리스트  이게 무슨 말인가 한참 찾았네요.. ㅋㅋㅋ  파일 이름으로 변경하면 좋을것 같아요

2023-01-04 01:25 UTC, Indoo-Park commented
> > @Indoo-Park 여기서도 <img alt="image" width="903" src="https://user-images.githubusercontent.com/51910605/210327403-3d527486-a1b7-495c-af73-f7ead51a59cc.png"> [process_manual](https://github.com/smartmind-team/tech-wiki/blob/main/project/thanosql/docs/process_manual.md) 참고하여
> > .pages와 `시작하기 -> ThanoSQL 워크스페이스 사용법 -> 4. 튜토리얼 가져오기 리스트`에 URL 추가, reference.md에도 추가해 주세요.
> 
> 시작하기 -> ThanoSQL 워크스페이스 사용법 -> 4. 튜토리얼 가져오기 리스트 이게 무슨 말인가 한참 찾았네요.. ㅋㅋㅋ 파일 이름을 추가하면 좋을 것 같아요

2023-01-04 02:18 UTC, Indoo-Park commented on docs/ko/how-to_guides/ThanoSQL_model/TFT.md
> +## __BUILD MODEL 예시_
엄허.. 수정완료 굿 캐치 감사합니다

2023-01-04 02:26 UTC, Indoo-Park commented on docs/ko/how-to_guides/ThanoSQL_model/TFT.md
> +- "target_col": 분류 모델의 목푯값이 담겨 있는 컬럼명 (str, default: 'target')
수정완료

2023-01-04 02:26 UTC, Indoo-Park commented on docs/ko/how-to_guides/ThanoSQL_model/TFT.md
> +- "min_encoder_length": 델이 예측할 때 사용할 과거 데이터의 최소 길이(time_idx). 기본값은 max_encoder_length 값에 맞춰집니다 (int, optional, default: 'max_encoder_length')
> min_encoder_length

델델델ㄷㄷㄷ 수정완료

2023-01-04 06:18 UTC, inwookie requested changes
@yeemh @Indoo-Park 

영문 수정해서 다시 commit 했습니다.

```sql
OPTIONS(
    (target_col=column_name),
    (time_idx_col=column_name),
    (max_encoder_length=VALUE),

파트는 한국어에도 똑같이 적용하면 될거 같아요

2023-01-04 06:30 UTC, inwookie commented on docs/ko/how-to_guides/ThanoSQL_model/TFT.md
> +[미래 전력 사용량 예측하기]({/ko/tutorials/thanosql_ml/timeseries/timeseries_forecasting.ipynb/})에서 "__PREDICT__" 구문 사용 예시를 확인하실 수 있습니다.
영문도 한번 확인해 주세요!

2023-01-04 06:30 UTC, inwookie commented on docs/ko/how-to_guides/ThanoSQL_model/TFT.md
> +*
@Indoo-Park 이것도 영문 확인 부탁 할게요!

2023-01-04 06:35 UTC, Indoo-Park commented on docs/ko/how-to_guides/ThanoSQL_model/TFT.md
> +    [overwrite={True|False}]
> max_encoder_length, max_prediction_length, allow_missing_timesteps 이 매개변수들은 꼭 써야하는 것들인가요?

기본 값이 있긴 하지만 데이터 마다 사용자가 원하는 예측 방법 마다 다르게 설정해줘야 합니다 

e.g. 사용자가 7일 데이터를 사용해서 다음날 하루 를 예측하고 싶다면 max_encoder_length=7 , max_prediction_length=1로 설정해줘야 하고 만약 시계열에 손실된 시간이 있다면 allow_missing_timesteps = True 로 해줘야 합니다. 

없어도 돌아갈 때 있고 안 돌아갈 때 있어요 (데이터 마다 달라서 꼭 지정해줘야 하는 옵션으로 ...)

2023-01-04 06:39 UTC, inwookie requested changes

2023-01-04 06:39 UTC, inwookie commented on docs/en/how-to_guides/ThanoSQL_model/TFT.md
> +## __PREDICT Example___
```suggestion
__PREDICT Example__
```

2023-01-04 06:40 UTC, jyoon0808 commented on docs/ko/how-to_guides/ThanoSQL_model/TFT.md
> +## __BUILD MODEL 예시_
Underscore가 앞쪽은 두개 뒷쪽은 한개입니다..!

2023-01-04 07:59 UTC, yeemh commented on docs/en/how-to_guides/ThanoSQL_model/TFT.md
> +## __PREDICT Example___
@Indoo-Park 한글에서도 확인부탁드립니다.

2023-01-04 08:35 UTC, yeemh approved these changes
HERE WE GO

2023-01-04 08:40 UTC, merged