Update query_manager.md
smartmind-team/thanosql-docs pull request #206
Opened 2023-08-17 04:51 UTC by yejinsss

# Description (개요) 

Please include a summary of the change and which statement has been created or fixed.

## Keep in Mind

If you are creating a new statement, your first commit should always be a copy of the statement(model, ThanoSQL, function) template. This will allow reviewers to see what has been changed from the template, making the review process much more efficient.

## Type of change (작업사항)

Please delete options that are not relevant and check out the type of change.

- [ ] Model statmenet creation 
- [ ] ThanoSQL statmenet creation 
- [ ] Function statmenet creation 
- [ ] Model statement fix 
- [ ] ThanoSQL statement fix 
- [ ] Function statement fix 

Following templates can be found from the [Tech-wiki Docs](https://github.com/smartmind-team/tech-wiki/tree/main/project/thanosql/docs). 

## Writing Convention

Make sure to check out the [Writing Convention](https://github.com/smartmind-team/tech-wiki/blob/main/project/thanosql/docs/writing_convention.md). 

## Review Process

Review should be conducted by at least two people.

2023-08-18 01:02 UTC, lazyduo requested changes
- 데이터베이스 탐색기에서 qm 스키마가 사라지고 임시 결과 테이블 표시하는 부분으로 대체 되었는데 해당 내용이 누락되었습니다. 
- 이미지 파일을 추가는 했는데 .md에 잘못써서 반영되지 않았습니다.
- mkdocs serve로 로컬에서 페이지 꼭 확인하면서 작업해주세요. 아래 처럼 줄바꿈 처리가 안되는 경우가 많습니다.
![image](https://github.com/smartmind-team/thanosql-docs/assets/71164591/a7ae0017-b422-4d55-8243-3da1fd37a770)
- 시간을 갖고 문서에 공을 들이세요. 부적절한 제목, 통일 되지 않은 용어, 불필요한 영어 사용 (ex Button) 등등 너무 고칠게 많아요.

@ss-won @yong313 1.5 문서에 반영할 내용 정리해서 같이 작성해주세요.

2023-08-18 01:02 UTC, lazyduo commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +데이터 베이스 탭을 클릭해 테이블 데이터 추가하기-> 테이블 추가하기를 클릭합니다.
데이터 베이스 탭 -> 데이터베이스 탐색기

다른 문서에서 사용된 용어와 통일해야합니다.

2023-08-18 01:02 UTC, lazyduo commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +테이블 추가하기 Drawer에서 새 테이블 직접 만들기를 클릭합니다.
Drawer는 다소 일반인에게 친숙한 표현이 아닙니다.

2023-08-18 01:02 UTC, lazyduo commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +#### 2) 스키마 생성 하는 법
소제목으로 '~생성 하는 법', '~만들기', '~생성하는 방법'이 혼재되어 있습니다.

2023-08-18 01:02 UTC, lazyduo commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +#### 컬럼 설정
![image](https://github.com/smartmind-team/thanosql-docs/assets/71164591/4c4ce6ee-bb78-474a-abf7-060236ac2355)

문서 구조를 고려해 '#'을 올바르게 사용하여 우측에 ToC가 올바르게 표시될 수 있게 해주세요.

2023-08-18 01:02 UTC, lazyduo commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +##### 1-2) 로컬 파일 업로드로 만들기
이상한 제목

2023-08-18 01:02 UTC, lazyduo commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +#### 1) 테이블 추가 하는 방법 - ①
①

2023-08-21 02:21 UTC, ss-won requested changes
1차 코멘트 남겼습니다. 확인 후 코멘트 및 반영부탁드립니다~

2023-08-21 02:21 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
line 40-42줄 데이터 뷰어 내용은 지워주세요~!

2023-08-21 02:21 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
`데이터 뷰어` 내용이 중복됩니다.

2023-08-21 02:21 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
![image](https://github.com/smartmind-team/thanosql-docs/assets/31684481/ca60f0d1-3f16-45fa-a9f4-6ceab74bafb4)
스키마 우측 + 버튼으로도 데이터 추가하기 진행할 수 있다는 내용도 함께 넣어주세요~

2023-08-21 02:21 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +데이터 베이스 탭을 클릭해 테이블 데이터 추가하기-> 테이블 추가하기를 클릭합니다.
해당 내용이 line67과 중복 됩니다.
아래 이미지와 다른 내용인 것 같아요

2023-08-21 02:21 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +테이블 추가하기 Drawer에서 새 테이블 직접 만들기를 클릭합니다.
[제안] 테이블 추가하기 창에서 `새 테이블 직접 만들기`를 선택한 후 다음 버튼을 클릭합니다.

2023-08-21 02:21 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +테이블 추가하기 -> 로컬 파일 업로드를 선택합니다.
line 91과 중복됩니다.
여기도 아래 이미지와 상관없는 내용인것 같아요

2023-08-21 02:21 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +③ 스키마 선택 : 테이블을 생성할  스키마를 선택할 수 있습니다.
```suggestion
③ 스키마 선택 : 테이블을 생성할 스키마를 선택할 수 있습니다. 

```

2023-08-21 02:21 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +##### 1-2) 로컬 파일 업로드로 만들기
[제안]
```suggestion
##### 1-2) 로컬 파일 업로드
```
```suggestion
##### 1-2) 로컬 파일 업로드를 통해 테이블 추가하기
```

2023-08-21 02:21 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +① 스키마 선택 : 테이블을 생성할  스키마를 선택할 수 있습니다.
```suggestion
① 스키마 선택 : 테이블을 생성할 스키마를 선택할 수 있습니다. 

```

2023-08-21 02:21 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +테이블 추가하기 Drawer에서 새 테이블 직접 만들기를 클릭합니다.
```suggestion
테이블 추가하기 창에서 새 테이블 직접 만들기를 선택한 후 다음 버튼을 클릭합니다.  
```

2023-08-21 02:21 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +⑤ Data Type(데이터 타입) : 해당 컬럼의 데이터 타입을 선택 할 수 있습니다.
해당 내용은 필수값이다. 라는 표현도 함께 있으면 좋을 것 같습니다.

2023-08-21 02:21 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +③ 이름 : 테이블 이름을 작성할 수 있습니다.
컬럼 이름과 다르게 초기 창에서는 이름 관련 validation 조건이 드러나지 않으니, 해당 내용에 추가적으로 언급하면 좋을 것 같습니다.

[예시]
```suggestion
③ 이름 : 테이블 이름을 작성할 수 있습니다. 테이블 이름은 문자, 숫자, 언더스코어를 포함 할 수 있으며 숫자로 시작할 수 없습니다.
```

2023-08-21 02:21 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +⑩ 완료 Button :  새 테이블 직접 만들기를 완료 할 수 있습니다.
```suggestion
⑩ 완료 Button : 새 테이블 직접 만들기를 완료할 수 있습니다. 
```

2023-08-21 02:21 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +- 직접 입력 :  컬럼을 직접 입력 할 수 있습니다.
```suggestion
- 직접 입력 : 컬럼을 직접 입력할 수 있습니다.  

```

2023-08-21 02:21 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +⑨ 완료 Button :  로컬 파일 업로드를 완료 할 수 있습니다.
```suggestion
⑨ 완료 Button : 로컬 파일 업로드를 완료할 수 있습니다.
```

2023-08-21 02:21 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +#### 2) 스키마 생성 하는 법
```suggestion
#### 2) 스키마 생성하기
```

2023-08-21 02:21 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +데이터 베이스 탭을 클릭해 테이블 데이터 추가하기-> 스키마 추가하기를 클릭합니다.
```suggestion
데이터 베이스 탭을 클릭해 테이블 데이터 추가하기 -> 스키마 추가하기를 클릭합니다.
```

2023-08-21 02:21 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +#### 2) 스키마 생성 하는 법
이건 실제 서비스에서도 ux writing 통일성을 맞추어야 할 것 같네요.
메뉴에서는 아래와 같이 안내하고 있는데
> 데이터 추가하기
> 스키마 생성하기

실제 스키마 생성하기 모달의 제목에는 `스키마 생성`으로 적혀 있습니다.
스키마 생성하기로 ux writing 통일하는게 어떨까요.

2023-08-21 02:21 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +쿼리 결과 테이블 내의 비정형 데이터를 확인할 수 있습니다. 비정형 파일의 경로가 저장된 컬럼을 선택 후 파일 형식(이미지, 비디오, 오디오)을 선택하여 비정형 데이터를 표시합니다. 하단의 페이지 이동 기능으로 한 번에 표시할 개수를 조절하고 다른 페이지로 이동할 수 있습니다.
해당 내용 내용에 이미지와 함께 아래 내용 구체적으로 설명하면 좋을 것 같아요! 이건 같이 적어보죠 :)..

- 미디어 타입 선택
- 대상 컬럼 선택
- 미디어 새창으로 열기

2023-08-21 02:28 UTC, ss-won commented
[추가 코멘트]
테이블 삭제하기 내용도 필요합니다

2023-08-22 06:37 UTC, yong313 approved these changes
고생하셨습니다.
리뷰 확인 부탁드립니다 👍

[추가 코멘트]
![스크린샷 2023-08-22 오후 4 11 16](https://github.com/smartmind-team/thanosql-docs/assets/85574104/30668336-50a0-4efd-81c8-acd3f11ef219)

1. Query Manager Docs 페이지 개요 순서 변경 제안
- 1. 쿼리 에디터 -> 에디터 기능 및 단축키, csv, 데이터뷰어 설명
- 2. 데이터베이스 탐색기 -> 데이터 추가하기 설명
- 3. 쿼리 로그 -> 상세 정보창


2. 데이터 삭제하기 섹션 추가
- 오전 FE 회의에서 나온 의견 
데이터 추가하기 다음 섹션으로 데이터 삭제하기 섹션을 추가하여 테이블 삭제 이외의 스키마 삭제하기 등을 고려해서 관리하는 건 어떨까요?

2023-08-22 06:37 UTC, yong313 commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +# __Query Manager 매뉴얼__[Title](https://github.com/smartmind-team/thanosql-docs/assets/31684481/ca60f0d1-3f16-45fa-a9f4-6ceab74bafb4)
테이블 추가하기 이미지입니다 (삭제!!)

2023-08-22 06:37 UTC, yong313 commented on docs/ko/getting_started/paas/workspace/query_manager.md
>  쿼리 결과 테이블 내의 비정형 데이터를 확인할 수 있습니다. 비정형 파일의 경로가 저장된 컬럼을 선택 후 파일 형식(이미지, 비디오, 오디오)을 선택하여 비정형 데이터를 표시합니다. 하단의 페이지 이동 기능으로 한 번에 표시할 개수를 조절하고 다른 페이지로 이동할 수 있습니다.
```데이터 뷰어 하단에는 페이지 이동 기능이 제공되어, 한 번에 표시되는 데이터의 개수를 조절할 수 있습니다. 이 기능을 사용하여 데이터 개수를 조정하면, 조정된 개수를 기반으로 페이지가 생성되며 각 페이지로 이동할 수 있습니다.```
좀 더 자세히 작성하여 전달하는 거 어떨까요?

2023-08-22 06:37 UTC, yong313 commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +****테이블을 삭제할 수도 있습니다.****
[제안](https://github.com/smartmind-team/thanosql-docs/pull/206#pullrequestreview-1583932723)

2023-08-22 06:37 UTC, yong313 commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +#### 2) 스키마 생성하기
스키마 생성하기 or 추가하기 통일 의견 부탁드립니다 예진님

2023-08-22 06:37 UTC, yong313 commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +자주 쓰는 테이블과 스키마를 추가할 수 있습니다.
자주 쓰는 테이블과 스키마라는 뜻이
데이터 추가 시 주로 사용하는 테이블 추가 & 스키마 추가를 뜻하는 건가요?
이 부분 문구가 좀 어색한 거 같습니다

```
ex)
자주 활용되는 기능 중 하나인 새로운 테이블과 스키마를 추가하는 방법은 간단합니다. 
먼저 새로운 테이블을 추가하는 방법은 두 가지로 나눌 수 있습니다.
```

2023-08-22 06:37 UTC, yong313 commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +데이터베이스 탐색기을 클릭해 테이블 데이터 추가하기-> 테이블 추가하기를 클릭합니다.
데이터베이스 탐색기 우측 상단에 위치한 데이터 추가하기 버튼 클릭 -> 테이블 추가하기를 클릭합니다.

QM의 sideNav에서 query log를 제외한 나머지 부분이 데이버베이스 탐색기 명칭을 가지고있다면,
데이터베이스 탐색기의 우측 상단에 위치한 데이터 추가하기 버튼이라는 설명이 필요할 거 같습니다!

2023-08-22 06:37 UTC, yong313 commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +⑥ Field : Data Type(데이터 타입)에 따라 달라지고, 사용 용도에 따라 사용할 수 있습니다.
데이터 타입에 따라 달라지는 내용을 좀 더 자세하게 적는 방향으로 수정하는 거 어떨까요?
```
ex)
Field : 선택한 데이터 타입에 따라, 필드(Field)의 사용자 입력 인터페이스(UI)가 조정되며, 해당 컬럼의 용도에 맞게 설정할 수 있습니다.
```

2023-08-22 06:37 UTC, yong313 commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +③ 이름 : 테이블 이름을 작성할 수 있습니다. 테이블 이름은 문자, 숫자, 언더스코어를 포함할 수 있으며 숫자로 시작할 수 없습니다.
[제안]
중복된 테이블 이름은 사용할 수 없고, 중복 된 테이블 이름을 사용 시 10번 완료 다음 단계로 진행 못한다는 내용 추가하는 거 어떤가요?

2023-08-22 06:37 UTC, yong313 commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +
개발할땐 몰랐는데 docs 작성하며 사용되는 기능의 이름이 통일감 없이 사용 되는 거 같습니다
6번에서 field라는 설명과 이미지가 기제되어있어 field의 영역이 명확하게 구분이 되는 거 같은데 
필드 추가 클릭 시 컬럼을 추가할 수 있습니다.가 좀 어색하게 느껴지는데,
컬럼 추가로 수정하는 건 어떤가요??

2023-08-22 06:37 UTC, yong313 commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +- 직접 입력 :  컬럼을 직접 입력할 수 있습니다.
직접 입력 : (빈칸) 컬럼을...
컬럼을 앞에 빈칸 삭제!

2023-08-22 06:37 UTC, yong313 commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +파일을 자동감지할 수도 있고, 직접 입력할 수도 있습니다.
여기도 업로드한 파일을....이라는 문구를 추가하는게 좋을 거 같습니다

2023-08-22 09:55 UTC, ss-won commented
> 고생하셨습니다. 리뷰 확인 부탁드립니다 👍
> 
> [추가 코멘트]
> 
> ![스크린샷 2023-08-22 오후 4 11 16](https://user-images.githubusercontent.com/85574104/262264530-30668336-50a0-4efd-81c8-acd3f11ef219.png)
> 
> 1. Query Manager Docs 페이지 개요 순서 변경 제안
> 
> * 1. 쿼리 에디터 -> 에디터 기능 및 단축키, csv, 데이터뷰어 설명
> * 2. 데이터베이스 탐색기 -> 데이터 추가하기 설명
> * 3. 쿼리 로그 -> 상세 정보창
> 
> 2. 데이터 삭제하기 섹션 추가
> 
> * 오전 FE 회의에서 나온 의견
>   데이터 추가하기 다음 섹션으로 데이터 삭제하기 섹션을 추가하여 테이블 삭제 이외의 스키마 삭제하기 등을 고려해서 관리하는 건 어떨까요?

**변경안**
![image](https://github.com/smartmind-team/thanosql-docs/assets/31684481/572409d0-855a-44c5-9cbe-9391592b0648)

저는 개인적으로 상단 분류 및 UX 메뉴 depth에 맞게 다음과 같이 배치하는게 맞다고 생각하는데..어떻게 생각하시나요..

2023-08-22 09:59 UTC, ss-won requested changes
추가 코멘트 남겼습니다. 아침에 같이 확인해요...

2023-08-22 09:59 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +
![image](https://github.com/smartmind-team/thanosql-docs/assets/31684481/f2ea7b14-a281-4dce-b124-709fa3836399)
통상적으로 필드=컬럼은 같은 의미긴 하지만, 저도 통일성있게 컬럼 추가로 변경하는게 더 적합하다고 생각합니다.

2023-08-22 09:59 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +⑥ Field : Data Type(데이터 타입)에 따라 달라지고, 사용 용도에 따라 사용할 수 있습니다.
```suggestion
⑥ 컬럼 옵션 : Data Type(데이터 타입)에 따라 조정할 수 있는 옵션이 달라지고, 해당 컬럼의 용도에 맞게 설정할 수 있습니다.
```
용태님 의견까지 반영하되 필드라는 명칭이 다소 적합하지 않는 것 같아 보여서 다음과 같은 제안 드립니다.
@yejinsss @yong313 의견 달아주세요~

2023-08-22 09:59 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +③ 이름 : 테이블 이름을 작성할 수 있습니다. 테이블 이름은 문자, 숫자, 언더스코어를 포함할 수 있으며 숫자로 시작할 수 없습니다.
```suggestion
③ 이름 : 생성하려는 테이블의 이름을 작성할 수 있습니다. 테이블 이름은 문자, 숫자, 언더스코어를 포함할 수 있으며 숫자로 시작할 수 없습니다. 같은 스키마 안에서는 중복된 이름의 테이블을 생성할 수 없습니다.
```
저는 용태님 의견 동의하는데, 10번 완료 다음 단계까진 언급하지 않고 같은 스키마 안에서 중복된 이름 사용 못한다 정도만 언급해도 괜찮을 것 같아요. @yejinsss @yong313

2023-08-22 09:59 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +데이터베이스 탐색기을 클릭해 테이블 데이터 추가하기-> 테이블 추가하기를 클릭합니다.
용태님 의견에 +a 하여 다음과 같은 제안드립니다.
```suggestion
데이터베이스 탐색기의 Database 우측에 위치한 **`+`** 버튼을 클릭해 테이블 데이터 추가하기 메뉴를 열고 테이블 추가하기를 클릭합니다.
```

2023-08-22 09:59 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +
```suggestion
```

2023-08-22 09:59 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +먼저 새로운 테이블을 추가하는 방법은 두 가지로 나눌 수 있습니다.
```suggestion
새로운 테이블과 스키마를 데이터베이스에 추가할 수 있는 기능입니다.
```

2023-08-22 09:59 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +먼저 새로운 테이블을 추가하는 방법은 두 가지로 나눌 수 있습니다.
- `자주 활용되는 기능`이라고 하니 이미 있는 듯한 뉘앙스여서 어색한 것 같아요
- 해당 파트는 명쾌하게 어떤 기능인지만 설명하고 넘어가면 될 것 같습니다.

2023-08-22 09:59 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +[![IMAGE](../../../img/getting_started/paas/workspace/qm_img_13.png){: style="max-height:none"}](../../../img/getting_started/paas/workspace/qm_img_13.png)
```suggestion
[![IMAGE](../../../img/getting_started/paas/workspace/qm_img_12.png){: style="max-height:none"}](../../../img/getting_started/paas/workspace/qm_img_12.png) 

```
이미지가 잘못 첨부되었습니다.

2023-08-23 01:22 UTC, yejinsss commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +데이터베이스 탐색기을 클릭해 테이블 데이터 추가하기-> 테이블 추가하기를 클릭합니다.
오 좀 더 구체적으로 적어주셔서 감사합니다

2023-08-23 01:38 UTC, yejinsss commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +[![IMAGE](../../../img/getting_started/paas/workspace/qm_img_13.png){: style="max-height:none"}](../../../img/getting_started/paas/workspace/qm_img_13.png)
이 부분은 수정 완료해습니다

2023-08-23 01:55 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
>  쿼리 결과 테이블 내의 비정형 데이터를 확인할 수 있습니다. 비정형 파일의 경로가 저장된 컬럼을 선택 후 파일 형식(이미지, 비디오, 오디오)을 선택하여 비정형 데이터를 표시합니다. 하단의 페이지 이동 기능으로 한 번에 표시할 개수를 조절하고 다른 페이지로 이동할 수 있습니다.
```suggestion
쿼리 결과 테이블 내의 비정형 데이터를 확인할 수 있습니다. 비정형 파일의 경로가 저장된 컬럼을 선택 후 파일 형식(이미지, 비디오, 오디오)을 선택하여 비정형 데이터를 표시합니다. 데이터 뷰어 하단에는 페이지 이동 기능이 제공되어 한 번에 표시되는 데이터의 개수를 조절할 수 있습니다. 
```

2023-08-23 02:10 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +① 스키마 이름 : 생성하려는 스키마의 이름을 입력할 수 있습니다.
```suggestion
① 스키마 이름 : 생성하려는 스키마의 작성할 수 있습니다. 스키마 이름은 문자, 숫자, 언더스코어를 포함할 수 있으며 숫자로 시작할 수 없습니다. 같은 데이터베이스 안에서는 중복된 이름의 스키마를 생성할 수 없습니다.
```

2023-08-23 02:12 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +⑤ 이름 : 테이블 이름을 작성할 수 있습니다. 테이블 이름은 문자, 숫자, 언더스코어를 포함할 수 있으며 숫자로 시작할 수 없습니다.
```suggestion
⑤ 이름 : 생성하려는 테이블의 이름을 작성할 수 있습니다. 테이블 이름은 문자, 숫자, 언더스코어를 포함할 수 있으며 숫자로 시작할 수 없습니다. 같은 스키마 안에서는 중복된 이름의 테이블을 생성할 수 없습니다.
```

2023-08-23 02:17 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +④ Name(이름) : 해당 컬럼 이름을 작성할 수 있습니다. (필수값입니다.)
```suggestion
④ Name(이름) : 해당 컬럼 이름을 작성할 수 있습니다. 필수로 입력해야하며 같은 테이블 안에서는 중복된 이름의 컬럼을 생성할 수 없습니다.
```

2023-08-23 02:18 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +⑤ Data Type(데이터 타입) : 해당 컬럼의 데이터 타입을 선택할 수 있습니다. (필수값입니다.)
```suggestion
⑤ Data Type(데이터 타입) : 해당 컬럼의 데이터 타입을 선택할 수 있습니다. 필수로 입력해야 합니다.

```

2023-08-23 02:25 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +⑧ 필드 추가 : 컬럼을 추가할 수 있습니다.
```suggestion
⑧ 컬럼 추가 : 컬럼을 추가할 수 있습니다. 

```

2023-08-23 02:33 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +### __데이터 뷰어__
```suggestion
#### __데이터 뷰어__

```

2023-08-23 02:33 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +### __단축키__
```suggestion
#### __단축키__

```

2023-08-30 08:55 UTC, nokchalatte commented on docs/en/getting_started/paas/workspace/query_manager.md
> +② Query Input Area: Input queries and execute/stop them. Supports [Keyboard Shortcuts](#keyboard-shortcuts).
```suggestion
② Query Input Area: Input queries and execute/stop them. Supports [keyboard shortcuts](#keyboard-shortcuts).

```

2023-08-30 08:55 UTC, nokchalatte commented on docs/en/getting_started/paas/workspace/query_manager.md
> +    The query editor uses the Monaco Editor, which is also used in VSCode. Most shortcuts are the same as those used in VSCode. Refer to the [link](https://en.docs.monaca.io/products_guide/monaca_ide
```suggestion
    The query editor uses Monaco Editor, which is also used in VSCode. Most shortcuts are the same as those used in VSCode. Please refer to the [link](https://en.docs.monaca.io/products_guide/monaca_ide/editor){:target="\_blank"} for a list of Monaco Editor's shortcuts.

```

2023-08-30 08:55 UTC, nokchalatte commented on docs/en/getting_started/paas/workspace/query_manager.md
> +Quickly understand the content of the data table.
```suggestion
Quickly understand the contents of the data table.

```

2023-08-30 08:55 UTC, nokchalatte commented on docs/en/getting_started/paas/workspace/query_manager.md
> +⑨ Canceling the Direct Creation of New Table.
```suggestion
⑨ Cancelation of "Create New Table Manually".

```

2023-08-30 08:55 UTC, nokchalatte commented on docs/en/getting_started/paas/workspace/query_manager.md
> +⑩ Completion of Direct Creation of New Table.
```suggestion
⑩ Completion of "Create New Table Manually".

```

2023-08-30 08:55 UTC, nokchalatte commented on docs/en/getting_started/paas/workspace/query_manager.md
> +After opening the add table window, select 'Local File Upload' and click Next.
```suggestion
After opening the "Add Table" window, select **Local File Upload** and click "Next".

```

2023-08-30 08:55 UTC, nokchalatte commented on docs/en/getting_started/paas/workspace/query_manager.md
> +In the "Add Table" window, select **Create New Table** and then click the Next button.
```suggestion
In the "Add Table" window, select **Create New Table** and then click the "Next" button.

```

2023-08-30 08:55 UTC, nokchalatte commented on docs/en/getting_started/paas/workspace/query_manager.md
> +- Write if Empty: Adds data when the existing table is empty.
```suggestion
- Write if Empty: Writes data only when the table does not exist already.

```

2023-08-30 08:55 UTC, nokchalatte commented on docs/en/getting_started/paas/workspace/query_manager.md
> +- Append to Table: Adds data to the existing table.
```suggestion
- Append to Table: Adds data on top of existing contents if the table already exists.

```

2023-08-30 08:55 UTC, nokchalatte commented on docs/en/getting_started/paas/workspace/query_manager.md
> +- Overwrite Table: Overwrites the content of the existing table.
```suggestion
- Overwrite Table: Overwrites the contents of the table if it already exists.

```

2023-08-30 08:55 UTC, nokchalatte commented on docs/en/getting_started/paas/workspace/query_manager.md
> +⑧ The local file upload is canceled.
```suggestion
⑧ Cancelation of "Local File Upload".

```

2023-08-30 08:55 UTC, nokchalatte commented on docs/en/getting_started/paas/workspace/query_manager.md
> +⑨ The local file upload is complete.
```suggestion
⑨ Completion of "Local File Upload".

```

2023-08-30 08:55 UTC, nokchalatte commented on docs/en/getting_started/paas/workspace/query_manager.md
> +In the Add Data menu, click on Create Schema to generate a new schema.
```suggestion
In the Add Data menu, click on "Create Schema" to generate a new schema.

```

2023-08-30 08:55 UTC, nokchalatte commented on docs/en/getting_started/paas/workspace/query_manager.md
> +② The schema creation is canceled.
```suggestion
② Cancelation of "Create Schema".

```

2023-08-30 08:55 UTC, nokchalatte commented on docs/en/getting_started/paas/workspace/query_manager.md
> +③ The schema creation is complete.
```suggestion
③ Completion of "Create Schema".

```

2023-08-30 08:55 UTC, nokchalatte commented on docs/en/getting_started/paas/workspace/query_manager.md
> +All queries executed in the Query Manager are logged and can be viewed in the query logs section. They are listed in descending order of creation time. The logs show the executed query statement and
```suggestion
All queries executed in Query Manager are logged and can be viewed in the "Query Logs" section. They are listed in descending order of creation time. The logs show the executed query statement and whether the execution was successful.

```

2023-08-30 08:55 UTC, nokchalatte commented on docs/en/getting_started/paas/workspace/query_manager.md
> +You can enter a query syntax to search for query logs that were executed with similar query syntax.
```suggestion
① You can enter a keyword to search for query logs that were executed with similar query syntax.

```

2023-08-30 08:55 UTC, nokchalatte commented on docs/en/getting_started/paas/workspace/query_manager.md
> +① Query Information: Displays the ID, success status, creation time, execution time, end time, and target table name of the query.
```suggestion
② Query Information: Displays the ID, success status, creation time, start execution time, end time, and destination table name of the query.

```

2023-08-30 08:55 UTC, nokchalatte commented on docs/en/getting_started/paas/workspace/query_manager.md
> +② Query Statement: Displays the executed query statement.
```suggestion
③ Query Statement: Displays the executed query statement.

```

2023-08-30 08:55 UTC, nokchalatte commented on docs/en/getting_started/paas/workspace/query_manager.md
> +③ Error Message: Displays error messages that occurred during query execution.
```suggestion
④ Error Message: Displays error messages that occurred during query execution.

```

2023-08-30 08:55 UTC, nokchalatte commented on docs/en/getting_started/paas/workspace/query_manager.md
> +④ Open as New Query: Opens the query editor tab with the content of the clicked query.
```suggestion
⑤ Open as New Query: Opens the query editor tab with the content of the clicked query.

```

2023-08-30 08:55 UTC, nokchalatte commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +테이블 추가하기 창에서 로컬 파일 업로드를 선택한 후 다음 버튼을 클릭합니다.
```suggestion
테이블 추가하기 창에서 **로컬 파일 업로드**를 선택한 후 다음 버튼을 클릭합니다.

```

2023-08-30 08:55 UTC, nokchalatte commented on docs/ko/getting_started/paas/workspace/query_manager.md
> +쿼리 구문을 입력하여 유사한 쿼리 구문으로 실행된 쿼리 로그를 검색할 수 있습니다.
```suggestion
① 쿼리 구문을 입력하여 유사한 쿼리 구문으로 실행된 쿼리 로그를 검색할 수 있습니다.

```

2023-08-30 08:55 UTC, nokchalatte commented on docs/ko/getting_started/paas/workspace/query_manager.md
Change numbering:

② 쿼리 정보 : 아이디, 성공 여부, 생성 시간, 실행 시간, 종료 시간, 대상 테이블 명을 표시합니다.

③ 쿼리 구문 : 실행한 쿼리 구문이 표시됩니다.

④ 에러 메시지 : 쿼리 실행 시 발생한 에러 메시지를 표시합니다.

⑤ 새 쿼리로 열기 : 해당 쿼리의 내용으로 쿼리 에디터 탭을 엽니다.

2023-08-30 10:28 UTC, lazyduo approved these changes

2023-08-30 10:29 UTC, merged