WIP Release v1.5.3
smartmind-team/thanosql-docs pull request #225
Opened 2024-03-26 01:12 UTC by lazyduo

v1.5.3 확인용

2024-03-26 01:21 UTC, lazyduo commented on docs/ko/getting_started/paas/workspace/file_manager.md
> +- 저장 용량 : 현재 사용 중인 저장 공간과 남은 용량을 확인합니다.
```suggestion
File Manager는 Workspace 저장 공간에 파일을 업로드하고 관리할 수 있는 기능을 제공합니다. 사용자는 파일과 폴더를 생성, 이동, 복사, 삭제할 수 있습니다. 또한 저장 용량 및 파일의 속성을 확인 할 수 있어 효율적인 파일 관리가 가능합니다.

!!! note “” 루트(root) 디렉토리는 Lab과 동일합니다.

[![IMAGE](../../../img/getting_started/paas/workspace/fm_img_1.png){: style="max-height:none"}](../../../img/getting_started/paas/workspace/fm_img_1.png)
```

2024-03-27 05:37 UTC, lazyduo reviewed
@yejinsss
'Storage Capacity'는 뭔가 어색한 용어네요. 영문 내용들은 괜찮아 보이는데 용어 검수는 정식 릴리즈 전에 한 번 해야할듯합니다.

2024-05-23 04:51 UTC, ss-won commented
## Process for Contributor

- [x] Write Draft (문서/번역 초안 작성)
- [x] [Check Writing Convention (작성 가이드 확인)](https://github.com/smartmind-team/tech-wiki/blob/main/project/thanosql/docs/writing_convention.md)
- [x] [Spelling check (맞춤법 검사 - KR)](http://speller.cs.pusan.ac.kr/)
- [ ] Resolve reviews (리뷰 반영)

2024-05-23 05:35 UTC, ss-won requested changes

2024-05-23 05:35 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/index.md
> +1. 신청 Plan
```suggestion
1. 신청 Plan
```

2024-05-23 05:35 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/index.md
>  [![IMAGE](../../../img/getting_started/img4.png){: style="max-height:none"}](../../../img/getting_started/img4.png)
../../../img/getting_started/img4.png

바꾸신 이미지 경로 안맞는거 같아요~ 다시 확인해보세요~
docs/ko/img/getting_started/paas/workspace/img4.png

2024-05-23 05:35 UTC, ss-won commented on docs/ko/img/getting_started/paas/workspace/img3.png
경로 체크
docs/ko/img/getting_started/img3.png <- 이 이미지가 대체되는 것이 맞음

2024-05-23 05:35 UTC, ss-won commented on docs/ko/img/getting_started/paas/workspace/img4.png
마찬가지로 경로체크

2024-05-23 05:35 UTC, ss-won commented on docs/ko/img/getting_started/paas/workspace/img5.png
이것도 경로체크 index page에 해당 안뜨는거 같아요
docs/ko/img/getting_started/img5.png <- 이 이미지가 대체되는 것이 맞을것같음

2024-05-28 02:04 UTC, ss-won requested changes

2024-05-28 02:04 UTC, ss-won commented on docs/ko/img/getting_started/paas/workspace/img3.png
이 이미지는 예전버전이랑 바꾸신 버전 다 중복으로 이미 있는 파일이니 지우도록 하겠습니다.

2024-05-28 02:04 UTC, ss-won commented on docs/ko/img/getting_started/paas/workspace/img4.png
여기도 삭제

2024-05-28 02:04 UTC, ss-won commented on docs/ko/img/getting_started/paas/workspace/img5.png
여기도 마찬가지로 삭제

2024-05-28 02:04 UTC, ss-won commented on docs/ko/img/getting_started/paas/workspace/img6.png
여기도 삭제

2024-05-28 02:04 UTC, ss-won commented on docs/ko/img/getting_started/paas/workspace/qm_img_12.png
![image](https://github.com/smartmind-team/thanosql-docs/assets/31684481/01e8624a-3c01-4be9-9970-90fbeade6f73)

이거 예전 이미지가가 내용이랑 align이 맞는거 같아요..

2024-05-28 02:04 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/index.md
> +- **File Manager** : Workspace에서 사용할 파일을 업로드하고 관리할 수 있는 기능을 제공합니다. 사용해 보려면 [file Manager 매뉴얼](file_manager.md)을 참조하세요.
```suggestion
- **File Manager** : Workspace에서 사용할 파일을 업로드하고 관리할 수 있는 기능을 제공합니다. 사용해 보려면 [File Manager 매뉴얼](file_manager.md)을 참조하세요.
```

2024-05-28 02:04 UTC, ss-won commented on docs/ko/img/getting_started/paas/workspace/qm_img_12.png
![image](https://github.com/smartmind-team/thanosql-docs/assets/31684481/fb92ec10-6382-489a-ad8f-7bd62df959a0)

이거 차라리 여기 있는 데이터 추가하기 번호랑 테이블 추가하기 강조표시 삭제한 이미지로 바꾸고 여기 부분은 예전 이미지 그대로 쓰는게 더 나아 보입니다.

2024-05-29 04:57 UTC, ss-won requested changes
index.md, query_manager.md 바뀐 내용으로 영문 변환도 해야할것 같아요..!

2024-05-29 04:57 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/index.md
>        - 신청한 티어, 플랜 분류, 요금제 가격을 확인합니다.
![image](https://github.com/smartmind-team/thanosql-docs/assets/31684481/660eb8ee-9294-4797-b297-3bae6a02e224)
주석처리만 하니까 신청 Plan이 다음과 같이 남아있는게 어색해서 다음과 같이 설명만 남기는게 어떨까요?
```suggestion
- 신청한 티어, 플랜 분류, 요금제 가격을 확인합니다.
```

2024-05-29 04:57 UTC, ss-won commented on docs/ko/getting_started/paas/workspace/file_manager.md
> +!!! note ""
```suggestion
!!! note
```

2024-05-29 04:57 UTC, ss-won commented on docs/en/getting_started/paas/workspace/file_manager.md
> +!!! note ""
```suggestion
!!! note
```

2024-05-29 07:22 UTC, ss-won approved these changes
LGTM(Look Good To Me) 고생하셨습니다.

내일 영어 코멘트 리뷰랑, 최종 리뷰 후에 merge 하면 될 것 같습니다.

2024-05-29 07:47 UTC, merged