영문화/네비게이션 메뉴 수정
smartmind-team/thanosql-docs pull request #66
Opened 2022-07-26 10:08 UTC by yeemh

해야 할 일
- [ ] 이미지, 이전/다음 문서 경로 수정
- [ ] 영어 문서 추가
- [ ] 폴더 구조 변경
- [ ] 폴더 구조 변경 후 네비게이션 수정 (이름 및 구조)

2022-07-27 03:57 UTC, lazyduo requested changes
1. image들은 locale 구분 없이 공통으로 쓰는게 좋을 것 같아요.
2. nav가 원래 다 수동인가요? 폴더 구조 잘 짜고, header 타이틀 달면 자동으로 만들어 주지 않나요?.. 다른 mkdocs 활용한 곳들은 따로 .pages를 안두는 것 같은데 처음에 이 방식으로 가져간 이유가 따로 있나요?

2022-07-27 05:15 UTC, sk37025 reviewed
ko, en 분리한 구조 변경 확인

2022-07-27 06:59 UTC, yeemh commented
> 1. image들은 locale 구분 없이 공통으로 쓰는게 좋을 것 같아요.
> 2. nav가 원래 다 수동인가요? 폴더 구조 잘 짜고, header 타이틀 달면 자동으로 만들어 주지 않나요?.. 다른 mkdocs 활용한 곳들은 따로 .pages를 안두는 것 같은데 처음에 이 방식으로 가져간 이유가 따로 있나요?

@lazyduo 
해당 답변 내용이 길어져서 clickup에 정리해두었습니다.
https://app.clickup.com/31080411/v/dc/xmfyv-1363/xmfyv-8563

2022-07-27 07:10 UTC, yeemh commented
> ko, en 분리한 구조 변경 확인

@sk37025 
기존 목차에 맞게 폴더 구조 수정하고 이미지 다시 분류해서 경로 수정 같이 진행해야 합니다.

2022-07-27 07:14 UTC, merged

2022-07-27 07:20 UTC, lazyduo commented
왜 머지가 진행 되었나요

2022-07-27 09:36 UTC, lazyduo commented
> > 1. image들은 locale 구분 없이 공통으로 쓰는게 좋을 것 같아요.
> > 2. nav가 원래 다 수동인가요? 폴더 구조 잘 짜고, header 타이틀 달면 자동으로 만들어 주지 않나요?.. 다른 mkdocs 활용한 곳들은 따로 .pages를 안두는 것 같은데 처음에 이 방식으로 가져간 이유가 따로 있나요?
> 
> @lazyduo 해당 답변 내용이 길어져서 clickup에 정리해두었습니다. https://app.clickup.com/31080411/v/dc/xmfyv-1363/xmfyv-8563

각 문서에 [title 메타 데이터](https://www.mkdocs.org/user-guide/writing-your-docs/#meta-data)를 달고, nav에서 title override 없이 파일명만으로 달아주는건 어떨까요? 이렇게 하는 이유는, ko, en에 따라 nav(.pages)는 변동이 없고 각 문서에서의 title 메타데이터 번역만으로 조절 할 수 있기 때문입니다. 번역에 신경쓸 범위도 docs의 .md들만 신경쓰고 싶은 이유도 있구요.

```md
---
title: My Document
summary: A brief description of my document.
authors:
    - Waylan Limberg
    - Tom Christie
date: 2018-07-10
some_url: https://example.com
---
```

2022-07-27 11:14 UTC, yeemh commented
> > > 1. image들은 locale 구분 없이 공통으로 쓰는게 좋을 것 같아요.
> > > 2. nav가 원래 다 수동인가요? 폴더 구조 잘 짜고, header 타이틀 달면 자동으로 만들어 주지 않나요?.. 다른 mkdocs 활용한 곳들은 따로 .pages를 안두는 것 같은데 처음에 이 방식으로 가져간 이유가 따로 있나요?
> > 
> > 
> > @lazyduo 해당 답변 내용이 길어져서 clickup에 정리해두었습니다. https://app.clickup.com/31080411/v/dc/xmfyv-1363/xmfyv-8563
> 
> @yeemh 정리해주신 문서 잘 확인했습니다.
> 
> 각 문서에 [title 메타 데이터](https://www.mkdocs.org/user-guide/writing-your-docs/#meta-data)를 달고, nav에서 title override 없이 파일명만으로 달아주는건 어떨까요? 이렇게 하는 이유는, ko, en에 따라 nav(.pages)는 변동이 없고 각 문서에서의 title 메타데이터 번역만으로 조절 할 수 있기 때문입니다. 번역에 신경쓸 범위도 `docs의 .md들`만 신경쓰고 싶은 이유도 있구요.
> 
> ```lisp
> ---
> title: My Document
> summary: A brief description of my document.
> authors:
>     - Waylan Limberg
>     - Tom Christie
> date: 2018-07-10
> some_url: https://example.com
> ---
> ```

해당 내용 적용되는지 테스트 해보겠습니다.

2022-07-28 02:13 UTC, yeemh commented
> > > > 1. image들은 locale 구분 없이 공통으로 쓰는게 좋을 것 같아요.
> > > > 2. nav가 원래 다 수동인가요? 폴더 구조 잘 짜고, header 타이틀 달면 자동으로 만들어 주지 않나요?.. 다른 mkdocs 활용한 곳들은 따로 .pages를 안두는 것 같은데 처음에 이 방식으로 가져간 이유가 따로 있나요?
> > > 
> > > 
> > > @lazyduo 해당 답변 내용이 길어져서 clickup에 정리해두었습니다. https://app.clickup.com/31080411/v/dc/xmfyv-1363/xmfyv-8563
> > 
> > 
> > @yeemh 정리해주신 문서 잘 확인했습니다.
> > 각 문서에 [title 메타 데이터](https://www.mkdocs.org/user-guide/writing-your-docs/#meta-data)를 달고, nav에서 title override 없이 파일명만으로 달아주는건 어떨까요? 이렇게 하는 이유는, ko, en에 따라 nav(.pages)는 변동이 없고 각 문서에서의 title 메타데이터 번역만으로 조절 할 수 있기 때문입니다. 번역에 신경쓸 범위도 `docs의 .md들`만 신경쓰고 싶은 이유도 있구요.
> > ```lisp
> > ---
> > title: My Document
> > summary: A brief description of my document.
> > authors:
> >     - Waylan Limberg
> >     - Tom Christie
> > date: 2018-07-10
> > some_url: https://example.com
> > ---
> > ```
> 
> 해당 내용 적용되는지 테스트 해보겠습니다.

@lazyduo

각 문서에 대한 제목은 메타데이터를 이용하여 각 md 파일로 관리하도록 하겠습니다.
문서 및 폴더간의 순서 문제는 파일(혹은 폴더)명에 숫자를 붙여 해결하도록 하겠습니다.

그런데 폴더명에 대해서는 메타데이터로 적용이 불가능하기 때문에 폴더명에 대한 부분은 
1. 동일 디렉토리 레벨에서 .pages로 관리하거나 
2. mkdocs.yml 파일에서 nav_translations 옵션으로 관리해주어야 할텐데 
신경써야할 범위를 줄이려면 yaml 파일 내에서 관리하는게 나아 보이니 2 번 방식으로 진행하도록 하겠습니다.

혹시 다른 생각하신 방법이 있으시다면 참고하도록 하겠습니다!