Created new syntax page: GET
smartmind-team/thanosql-docs pull request #85
Opened 2022-08-25 02:40 UTC by inwookie

GET syntax page 만들었습니다.

2022-08-25 02:52 UTC, yeemh requested changes

2022-08-25 02:52 UTC, yeemh commented on docs/ko/how-to_guides/syntax_list.md
> +        <h3>저장한 모델 확인하기</h3>
위에랑 제목이 동일해서 다르게 작성하는게 좋겠네요

2022-08-25 02:52 UTC, yeemh commented on docs/ko/how-to_guides/syntax_list.md
> +        <h3>저장한 모델 확인하기</h3>
이제보니 복사하고 수정을 안한..?🥺

2022-08-25 02:53 UTC, inwookie commented on docs/ko/how-to_guides/syntax_list.md
> +        <h3>저장한 모델 확인하기</h3>
와우!

2022-08-25 02:56 UTC, yeemh commented on docs/ko/how-to_guides/ThanoSQL_query/GET_SYNTAX.md
> +```sql
CREATE_TABLE_SYNTAX에 
```sql
CREATE TABLE [사용자 지정 데이터 테이블 이름]
USING [사용할 인공지능 모델]
OPTIONS (overwrite=True) -- default:False
FROM [사용할 데이터 세트]
```
여기도 줄바꿈으로 통일해야겠네요
메모메모

2022-08-25 03:01 UTC, yeemh reviewed
lgtm

2022-08-25 03:01 UTC, yeemh approved these changes

2022-08-31 04:58 UTC, sk37025 approved these changes

2022-08-31 04:58 UTC, merged